name: Checkstyle

on: 
  push:
    branches: [ "*" ]
    paths: [ '**/*.java' ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "master", "develop" ]
    paths: [ '**/*.java' ]

jobs:
  checkstyle:
    name: Checkstyle Validation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      statuses: write
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Run Checkstyle
        id: checkstyle
        run: |
          mvn checkstyle:check
          EXIT_CODE=$?
          if [ $EXIT_CODE -ne 0 ]; then
            echo "::error::Checkstyle violations found"
            exit $EXIT_CODE
          fi
          
      - name: Update PR Status
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.name,
              pull_number: context.issue.number,
              body: 'Checkstyle violations must be fixed before merging.',
              event: 'REQUEST_CHANGES'
            })