name: Checkstyle
on: 
  push:
    branches:
      - "*"    # Run on all branches
    paths:
      - '**/*.java'
  pull_request:
    branches: ["master", "develop"]
    paths:
      - '**/*.java'

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Allow status updates
      pull-requests: write
      checks: write        # Required for status checks
      statuses: write     # Required for commit status
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: '**/*.java'
          
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
          
      - name: Run Checkstyle
        id: checkstyle
        run: mvn checkstyle:check
        continue-on-error: false

      - name: Block Changes on Failure
        if: steps.checkstyle.outcome != 'success'
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Checkstyle violations found. Changes blocked until formatting is fixed.');