name: Checkstyle

on: 
  push:
    branches: [ "*" ]
    paths: [ '**/*.java' ]
  pull_request:
    branches: [ "master", "develop" ]
    paths: [ '**/*.java' ]

jobs:
  checkstyle:
    name: Checkstyle Validation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      statuses: write
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Run Checkstyle
        id: checkstyle
        run: |
          mvn checkstyle:check
          if [ $? -ne 0 ]; then
            echo "Checkstyle violations found"
            exit 1
          fi
          
      - name: Status Check
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            if (context.job.status !== 'success') {
              core.setFailed('Checkstyle violations found. Fix formatting issues before merging.')
              process.exit(1)
            }